# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        aktualita_thumb:

            # adjust the image quality to 95%
            quality: 95

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [255, 144], mode: outbound }

        # the name of the "filter set"
        aktualita_full_thumb:

            # adjust the image quality to 95%
            quality: 95

            # list of transformations to apply (the "filters")
            filters:
                auto_rotate: ~
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 913, 515 ], mode: outbound }